"""
Generates tiny base64 blur placeholders for every image the site renders.

next/image shows these instantly while the full image loads, so the lightbox and
the grid never flash an empty box — which matters here, because the embroidery
detail is the whole point of the page.

Run after regenerating images: python3 scripts/make_blur.py
"""
import base64
import io
import json
import os

from PIL import Image

OUT = "lib/blur.ts"


def blur_uri(path, width=10):
    img = Image.open(path).convert("RGB")
    h = max(1, round(width * img.height / img.width))
    img = img.resize((width, h), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=45)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    with open("scripts/placeholders.json") as fh:
        spec = json.load(fh)

    entries = {}
    for item in spec:
        public_path = "/images/" + item["path"]
        disk = os.path.join("public/images", item["path"])
        entries[public_path] = blur_uri(disk)

    lines = [
        "/**",
        " * Generated by scripts/make_blur.py — do not edit by hand.",
        " *",
        " * Tiny base64 previews keyed by public image path, so next/image can paint",
        " * something immediately instead of an empty box while the full image loads.",
        " */",
        "",
        "export const blurDataUrls: Record<string, string> = {",
    ]
    for k, v in entries.items():
        lines.append("  '%s':\n    '%s'," % (k, v))
    lines.append("};")
    lines.append("")
    lines.append("/** Blur preview for an image path, or undefined if none was generated. */")
    lines.append("export const blurFor = (src: string): string | undefined => blurDataUrls[src];")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print("wrote %s with %d entries" % (OUT, len(entries)))


if __name__ == "__main__":
    main()
